language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - '$HOME/.m2/repository'
  
#before_install:
# - chmod +x gradlew

script:
  - mvn clean package
  
after_success:
  - cd ./target
  - git init
  - git config user.name "zhezhiyong"
  - git config user.email "zhezhiyong@163.com"
  - git add spring-boot-jsp.war
  - git commit -m "pack"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - test
env:
 global:
   - GH_REF: github.com/zheng-zy/test-travis-ci-maven.git

   notifications:
  email: false